services:
  backend:
    image: ghcr.io/rangelovkiril/hacktues12-backend:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ramp-data:/app/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  frontend:
    image: ghcr.io/rangelovkiril/hacktues12-frontend:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_POLL_INTERVAL: "60"
      WATCHTOWER_ROLLING_RESTART: "true"
      TZ: "Europe/Sofia"

volumes:
  ramp-data:
